# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-09 08:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0048_auto_20180314_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='show_sponsorship_document',
            field=models.BooleanField(default=False),
        ),
    ]
