# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-15 12:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtaildocs', '0007_merge'),
        ('website', '0049_auto_20180509_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='footer_cookie_statement_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.Document'),
        ),
    ]
