# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-09 09:21
from __future__ import unicode_literals

from django.db import migrations, models
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0049_homepage_show_sponsorship_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='speaker',
            name='description_bg',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='speaker',
            name='description_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='speaker',
            name='rich_description',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='speaker',
            name='rich_description_bg',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='speaker',
            name='rich_description_en',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='speaker',
            name='talk_description',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='speaker',
            name='talk_description_bg',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='speaker',
            name='talk_description_en',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True, null=True),
        ),
    ]
