# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-09 11:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0051_homepage_about_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='OldPartners',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
            ],
            options={
                'abstract': False,
                'ordering': ['sort_order'],
            },
        ),
        migrations.AddField(
            model_name='homepage',
            name='show_old_partners',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='oldpartners',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='old_partners', to='website.HomePage'),
        ),
        migrations.AddField(
            model_name='oldpartners',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='website.Partner'),
        ),
    ]
