# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-16 15:31
from __future__ import unicode_literals

from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0052_blog_blogpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='end_time',
            field=models.DateTimeField(default=timezone.now()),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='lecture',
            name='speaker',
        ),
        migrations.AddField(
            model_name='lecture',
            name='speaker',
            field=models.ManyToManyField(related_name='lecures', to='website.Speaker'),
        ),
    ]
