# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-17 12:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0053_auto_20180816_1531'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lecture',
            old_name='speaker',
            new_name='speakers',
        ),
    ]
