# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-19 08:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0056_auto_20180903_0918'),
    ]

    operations = [
        migrations.AddField(
            model_name='speaker',
            name='facebook_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='speaker',
            name='linked_in_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='speaker',
            name='twitter_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
