# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-09-08 16:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0060_auto_20190907_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='is_break',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lecture',
            name='is_event',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='speakers',
            field=models.ManyToManyField(blank=True, related_name='lectures', to='website.Speaker'),
        ),
    ]
