# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-09-08 22:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0061_auto_20190908_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='is_registration',
            field=models.BooleanField(default=False),
        ),
    ]
