# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-09-08 22:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0062_lecture_is_registration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lecture',
            old_name='is_break',
            new_name='is_coffee_break',
        ),
        migrations.AddField(
            model_name='lecture',
            name='is_lunch',
            field=models.BooleanField(default=False),
        ),
    ]
